import { Injectable } from '@angular/core';
import { Article, Articles } from './shared/interfaces/Articles';
import { HttpClient } from '@angular/common/http';
import { Observable, filter, map } from 'rxjs';

@Injectable({
  providedIn: 'root'
})
export class DataService {

  constructor(private http: HttpClient) { }

  getArticles(pageNo: number = 0, tag?: string): Observable<Articles> {

    var offset = pageNo * 10;

    if (!!tag) {
      var url = `https://api.realworld.io/api/articles?limit=10&offset=${offset}&tag=${tag}`;
    } else {
      var url = `https://api.realworld.io/api/articles?limit=10&offset=${offset}`;
    }
    return this.http.get<Articles>(url);
  }

  getTags(): Observable<string[]> {
    var url = 'https://api.realworld.io/api/tags';
    return this.http.get<Tags>(url).pipe(map(res => res.tags));
  }
}

// Generated by https://quicktype.io

export interface Tags {
  tags: string[];
}
