// Generated by https://quicktype.io

export interface Articles {
  articles:      Article[];
  articlesCount: number;
}

export interface Article {
  slug:           string;
  title:          string;
  description:    string;
  body:           string;
  tagList:        string[];
  createdAt:      string;
  updatedAt:      string;
  favorited:      boolean;
  favoritesCount: number;
  author:         Author;
}

export interface Author {
  username:  Username;
  bio:       null;
  image:     string;
  following: boolean;
}

export enum Username {
  AnahBenešová = "Anah Benešová",
}
